spring:
  application:
    name: zuul-gateway
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka

server:
  port: 8082

zuul:
  strip-prefix: true #转发路径截断匹配前缀
#  prefix: "/api"
  add-proxy-headers: false
  set-content-length: true
  semaphore:
    max-semaphores: 600

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
ribbon:
  ReadTimeout: 240000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eager-load:
    enabled: true
    clients: micro-service